### ISSUE TITLE
Creation of badges?

### ISSUE THREAD

**Issue by bavovanachte** [melexis/warnings-plugin#6]
Would it be a good idea to include the creation of badges in this project as well?

At the moment, I am creating my pylint badges like this (in gitlab):

```yml
pylint_full:
  <<: *pylint_setup
  script:
    - pylint --rcfile=pylint.rc src/PSF90372_Test_cases/*.py | tee pylint_score.txt
  after_script:
    - export PYLINT_SCORE=`sed -n 's~Your code has been rated at \([^/]*\).*~\1~p' pylint_score.txt`
    - wget https://img.shields.io/badge/pylint-$PYLINT_SCORE%2F10.0-blue.svg
    - mv *.svg pylint.svg
  allow_failure: true
  artifacts:
    paths:
    - pylint.svg
    when: always
```

Downsides of this are that:

- It depends on an external service (which could be unstable)
- Is fairly primitive (ATM, I just generate a blue badge, the colour doesn't depend on the score)

@Letme what do you think?
